<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="FileServerTest" tests="1" skipped="0" failures="1" errors="0" timestamp="2022-09-16T17:36:32" hostname="ev-i1.kzn.21-school.ru" time="16.613">
  <properties/>
  <testcase name="start" classname="FileServerTest" time="16.613">
    <failure message="java.lang.AssertionError: Error in test #3&#10;&#10;Infinite loop detected.&#10;Last 90 lines your program printed have 5 blocks of 18 lines of the same text.&#10;&#10;Please find below the output of your program during this failed test.&#10;Note that the '&gt;' character indicates the beginning of the input line.&#10;&#10;---&#10;&#10;stdout:&#10;Server started!&#10;Exception OK&#10;Client started!&#10;client accepted&#10;Enter action (1 - get a file, 2 - save a file, 3 - delete a file): &gt; 2&#10;Enter name of the file: &gt; test_purpose_test1.txt&#10;Enter name of the file to be saved on server:&gt;&#10;&#10;stderr:&#10;java.net.BindException: Address already in use&#10;&#9;at java.base/sun.nio.ch.Net.bind0(Native Method)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:555)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:544)&#10;&#9;at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)&#10;&#9;at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)&#10;&#9;at server.PortListening.run(PortListening.java:31)&#10;java.net.BindException: Address already in use&#10;&#9;at java.base/sun.nio.ch.Net.bind0(Native Method)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:555)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:544)&#10;&#9;at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)&#10;&#9;at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)&#10;&#9;at server.PortListening.run(PortListening.java:31)&#10;java.net.BindException: Address already in use&#10;&#9;at java.base/sun.nio.ch.Net.bind0(Native Method)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:555)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:544)&#10;&#9;at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)&#10;&#9;at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)&#10;&#9;at server.PortListening.run(PortListening.java:31)&#10;java.net.BindException: Address already in use&#10;&#9;at java.base/sun.nio.ch.Net.bind0(Native Method)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:555)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:544)&#10;&#9;at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)&#10;&#9;at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)&#10;&#9;at server.PortListening.run(PortListening.java:31)&#10;java.net.BindException: Address already in use&#10;&#9;at java.base/sun.nio.ch.Net.bind0(Native Method)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:555)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:544)&#10;&#9;at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)&#10;&#9;at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)&#10;&#9;at server.PortListening.run(PortListening.java:31)&#10;java.net.BindException: Address already in use&#10;&#9;at java.base/sun.nio.ch.Net.bind0(Native Method)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:555)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:544)&#10;&#9;at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)&#10;&#9;at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)&#10;&#9;at server.PortListening.run(PortListening.java:31)&#10;java.net.BindException: Address already in use&#10;&#9;at java.base/sun.nio.ch.Net.bind0(Native Method)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:555)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:544)&#10;&#9;at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)&#10;&#9;at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)&#10;&#9;at server.PortListening.run(PortListening.java:31)&#10;java.net.BindException: Address already in use&#10;&#9;at java.base/sun.nio.ch.Net.bind0(Native Method)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:555)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:544)&#10;&#9;at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)&#10;&#9;at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)&#10;&#9;at server.PortListening.run(PortListening.java:31)&#10;java.net.BindException: Address already in use&#10;&#9;at java.base/sun.nio.ch.Net.bind0(Native Method)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:555)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:544)&#10;&#9;at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)&#10;&#9;at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)&#10;&#9;at server.PortListening.run(PortListening.java:31)&#10;java.net.BindException: Address already in use&#10;&#9;at java.base/sun.nio.ch.Net.bind0(Native Method)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:555)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:544)&#10;&#9;at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)&#10;&#9;at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)&#10;&#9;at server.PortListening.run(PortListening.java:31)&#10;java.net.BindException: Address already in use&#10;&#9;at java.base/sun.nio.ch.Net.bind0(Native Method)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:555)&#10;&#9;at java.base/sun.nio.ch.Net.bind(Net.java:544)&#10;&#9;at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)&#10;&#9;at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)&#10;&#9;at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)&#10;Exception in thread &quot;Thread-5&quot; org.hyperskill.hstest.dynamic.security.ExitException: Tried to exit with status 0.&#10;&#9;at org.hyperskill.hstest.dynamic.output.InfiniteLoopDetector.fail(InfiniteLoopDetector.java:155)&#10;&#9;at org.hyperskill.hstest.dynamic.output.InfiniteLoopDetector.checkInfLoopLines(InfiniteLoopDetector.java:131)&#10;&#9;at org.hyperskill.hstest.dynamic.output.InfiniteLoopDetector.write(InfiniteLoopDetector.java:56)&#10;&#9;at org.hyperskill.hstest.dynamic.output.OutputMock.write(OutputMock.java:49)&#10;&#9;at java.base/java.io.OutputStream.write(OutputStream.java:162)&#10;&#9;at java.base/java.io.PrintStream.write(PrintStream.java:568)&#10;&#9;at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)&#10;&#9;at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)&#10;&#9;at java.base/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:111)&#10;&#9;at java.base/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:178)&#10;&#9;at java.base/java.io.PrintStream.writeln(PrintStream.java:723)&#10;&#9;at java.base/java.io.PrintStream.println(PrintStream.java:1051)&#10;&#9;at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:763)&#10;&#9;at java.base/java.lang.Throwable.printStackTrace(Throwable.java:673)&#10;&#9;at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)&#10;&#9;at java.base/java.lang.Throwable.printStackTrace(Throwable.java:650)&#10;&#9;at server.PortListening.run(PortListening.java:36)" type="java.lang.AssertionError">java.lang.AssertionError: Error in test #3

Infinite loop detected.
Last 90 lines your program printed have 5 blocks of 18 lines of the same text.

Please find below the output of your program during this failed test.
Note that the '&gt;' character indicates the beginning of the input line.

---

stdout:
Server started!
Exception OK
Client started!
client accepted
Enter action (1 - get a file, 2 - save a file, 3 - delete a file): &gt; 2
Enter name of the file: &gt; test_purpose_test1.txt
Enter name of the file to be saved on server:&gt;

stderr:
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.&lt;init&gt;(ServerSocket.java:167)
Exception in thread &quot;Thread-5&quot; org.hyperskill.hstest.dynamic.security.ExitException: Tried to exit with status 0.
	at org.hyperskill.hstest.dynamic.output.InfiniteLoopDetector.fail(InfiniteLoopDetector.java:155)
	at org.hyperskill.hstest.dynamic.output.InfiniteLoopDetector.checkInfLoopLines(InfiniteLoopDetector.java:131)
	at org.hyperskill.hstest.dynamic.output.InfiniteLoopDetector.write(InfiniteLoopDetector.java:56)
	at org.hyperskill.hstest.dynamic.output.OutputMock.write(OutputMock.java:49)
	at java.base/java.io.OutputStream.write(OutputStream.java:162)
	at java.base/java.io.PrintStream.write(PrintStream.java:568)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
	at java.base/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:111)
	at java.base/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:178)
	at java.base/java.io.PrintStream.writeln(PrintStream.java:723)
	at java.base/java.io.PrintStream.println(PrintStream.java:1051)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:763)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:673)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:650)
	at server.PortListening.run(PortListening.java:36)
	at org.junit.Assert.fail(Assert.java:88)
	at org.hyperskill.hstest.stage.StageTest.start(StageTest.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
</failure>
  </testcase>
  <system-out><![CDATA[?[1;31m
Start test 1?[0m
Server started!
Exception OK
Client started!
client accepted
Enter action (1 - get a file, 2 - save a file, 3 - delete a file): > exit
?[1;31m
Start test 2?[0m
?[1;31m
Start test 3?[0m
Server started!
Exception OK
Client started!
client accepted
Enter action (1 - get a file, 2 - save a file, 3 - delete a file): > 2
Enter name of the file: > test_purpose_test1.txt
Enter name of the file to be saved on server:> 
]]></system-out>
  <system-err><![CDATA[Exception in thread "Thread-4" org.hyperskill.hstest.dynamic.security.ExitException: Tried to exit with status 0.
	at org.hyperskill.hstest.dynamic.security.TestingSecurityManager.checkExit(TestingSecurityManager.java:50)
	at java.base/java.lang.Runtime.exit(Runtime.java:113)
	at java.base/java.lang.System.exit(System.java:1860)
	at server.Session.run(Session.java:39)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
	at server.PortListening.run(PortListening.java:31)
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
Exception in thread "Thread-5" org.hyperskill.hstest.dynamic.security.ExitException: Tried to exit with status 0.
	at org.hyperskill.hstest.dynamic.output.InfiniteLoopDetector.fail(InfiniteLoopDetector.java:155)
	at org.hyperskill.hstest.dynamic.output.InfiniteLoopDetector.checkInfLoopLines(InfiniteLoopDetector.java:131)
	at org.hyperskill.hstest.dynamic.output.InfiniteLoopDetector.write(InfiniteLoopDetector.java:56)
	at org.hyperskill.hstest.dynamic.output.OutputMock.write(OutputMock.java:49)
	at java.base/java.io.OutputStream.write(OutputStream.java:162)
	at java.base/java.io.PrintStream.write(PrintStream.java:568)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
	at java.base/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:111)
	at java.base/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:178)
	at java.base/java.io.PrintStream.writeln(PrintStream.java:723)
	at java.base/java.io.PrintStream.println(PrintStream.java:1051)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:763)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:673)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:650)
	at server.PortListening.run(PortListening.java:36)
]]></system-err>
</testsuite>
